language: julia
os:
  - linux
#   - osx
julia:
  - 1.0.4
notifications:
  email: false
matrix:
  allow_failures:
    - julia: nightly
after_success:
  - julia -e julia -e 'Pkg.add("Documenter")'
  - julia -e 'cd(Pkg.dir("EDFPlus")); include(joinpath("docs", "make.jl"))'
  - julia -e 'cd(Pkg.dir("EDFPlus")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
  - julia -e 'cd(Pkg.dir("EDFPlus")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(process_folder())'

